Repository DK-SEP4-S25-VIAUC/Frontend-Service, pull requests merged in 2025-05, with the labels that each got.

#39 First build with first iteration ci/cd
  .github/workflows/docker-build-publish.yml
  .github/workflows/lint-check.yml
  .github/workflows/unit-tests.yml
Labels: release

#43 Update soilHumidityLatestApi.js
  WebClient/src/api/soilHumidityLatestApi.js
Labels: bug

#57 Feature/remote watering
  WebClient/package-lock.json
  WebClient/package.json
  WebClient/src/App.css
  WebClient/src/App.jsx
  WebClient/src/api/soilHumidityLatestApi.js
  WebClient/src/api/waterReadingLatestApi.js
  WebClient/src/api/wateringApi.js
  WebClient/src/components/quick-controls/QuickControlCard.jsx
  WebClient/src/components/quick-controls/QuickControlCard.test.jsx
  WebClient/src/components/quick-controls/toggles/AddDevice.jsx
  WebClient/src/components/quick-controls/toggles/ToggleLight.jsx
  WebClient/src/components/quick-controls/toggles/ToggleVentilation.jsx
  WebClient/src/components/quick-controls/toggles/ToggleWaterPlant.jsx
  WebClient/src/components/quick-controls/toggles/ToggleWaterPlant.test.jsx
  WebClient/src/components/soil-humidity/SoilHumidityLatestCard.test.jsx
  WebClient/src/components/water-reading/WaterReadingLatestCard.jsx
  WebClient/src/components/water-reading/WaterReadingLatestCard.test.jsx
  WebClient/src/hooks/water-reading/useLatestWaterReading.js
  WebClient/src/hooks/watering/useWateringRequest.js
  WebClient/src/pages/landing-page/LandingPage.jsx
  WebClient/src/pages/navbar/Navbar.jsx
Labels: feature

#62 Feature/water history activity
  WebClient/package-lock.json
  WebClient/package.json
  WebClient/src/App.jsx
  WebClient/src/api/soilHumidityLatestApi.js
  WebClient/src/api/waterReadingsApi.js
  WebClient/src/components/activity-history/ActivityHistoryCard.jsx
  WebClient/src/components/activity-history/ActivityHistoryCard.test.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterLevelInfo.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterLevelInfo.test.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterReadingLatest.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterReadingLatest.test.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterTankDisplay.jsx
  WebClient/src/components/activity-history/activity-history-card/WaterTankDisplay.test.jsx
  WebClient/src/components/graph/LineGraph.jsx
  WebClient/src/components/water-reading/WaterReadingLatestCard.jsx
  WebClient/src/components/water-reading/WaterReadingLatestCard.test.jsx
  WebClient/src/hooks/activity-history/useWaterReadings.js
  WebClient/src/pages/landing-page/LandingPage.jsx
Labels: feature

#64 Added Air Humidity Latest Display
  WebClient/src/api/airHumidityLatestApi.js
  WebClient/src/components/air-humidity/AirHumidityLatestCard.jsx
  WebClient/src/components/air-humidity/AirHumidityLatestCard.test.jsx
  WebClient/src/components/air-humidity/air-humidity-card/Header.jsx
  WebClient/src/components/air-humidity/air-humidity-card/Header.test.jsx
  WebClient/src/components/soil-humidity/SoilHumidityLatestCard.jsx
  WebClient/src/components/soil-humidity/soil-humidity-card/HumidityDisplay.jsx
  WebClient/src/components/soil-humidity/soil-humidity-card/HumidityDisplay.test.jsx
  WebClient/src/hooks/air-humidity/useLatestAirHumidity.jsx
  WebClient/src/pages/landing-page/LandingPage.jsx
Labels: feature

#66 Feature/humidity history graph
  WebClient/init-git.sh
  WebClient/package-lock.json
  WebClient/package.json
  WebClient/src/api/soilHumidityHistoryApi.js
  WebClient/src/components/calender/CalenderModal.jsx
  WebClient/src/components/calender/GraphCalenderDisplay.jsx
  WebClient/src/components/calender/calender.css
  WebClient/src/components/graph/SoilLineGraph.jsx
  WebClient/src/components/soil-humidity/soil-humidity-history/SoilHumidityHistoryCard.jsx
  WebClient/src/components/soil-humidity/soil-humidity-history/SoilHumidityHistoryCard.test.jsx
  WebClient/src/hooks/soil-humidity/useHistorySoilHumidity.js
  WebClient/src/hooks/useCalender.js
  WebClient/src/pages/landing-page/LandingPage.jsx
  WebClient/tests/unit/soilHumidityHistoryApi.test.jsx
Labels: feature

#68 Feature/latest temperature
  WebClient/index.html
  WebClient/package-lock.json
  WebClient/package.json
  WebClient/src/App.jsx
  WebClient/src/api/wateringApi.js
  WebClient/src/components/Dashboard/Widget/WidgetBodyTemplate.jsx
  WebClient/src/components/Dashboard/Widget/WidgetContentTemplate.jsx
  WebClient/src/components/Dashboard/Widget/WidgetHeaderTemplate.jsx
  WebClient/src/components/quick-controls/QuickControlCard.jsx
  WebClient/src/components/quick-controls/QuickControlCard.test.jsx
  WebClient/src/components/quick-controls/toggles/ToggleWaterPlant.jsx
  WebClient/src/components/quick-controls/toggles/ToggleWaterPlant.test.jsx
  WebClient/src/components/soil-humidity/SoilHumidityInput.jsx
  WebClient/src/components/temperature/TemperatureWidget.jsx
  WebClient/src/components/temperature/TemperatureWidget.test.jsx
  WebClient/src/hooks/Animation/useMinimumAnimation.js
  WebClient/src/hooks/temperature/useGetTemperatureLatest.jsx
  WebClient/src/hooks/watering/useWateringRequest.js
  WebClient/src/pages/landing-page/LandingPage.jsx
  WebClient/src/pages/navbar/Navbar.jsx
Labels: feature

#70 fix
  WebClient/src/components/manual-watering/ManualWateringCard.jsx
Labels: bug

#73 Fixed Deployment workflow
  .github/workflows/deploy.yaml
Labels: bug, release

#74 changes to all widget on dashboard
  WebClient/src/components/manual-watering/ManualWateringCard.jsx
  WebClient/src/components/quick-controls/QuickControlCard.jsx
  WebClient/src/components/soil-humidity/SoilHumidityAlert.jsx
  WebClient/src/components/soil-humidity/SoilHumidityInput.jsx
  WebClient/src/components/watering-automatic/AutomaticWateringCard.jsx
  WebClient/src/pages/landing-page/LandingPage.jsx
Labels: bug

#75 Dev
  WebClient/src/components/manual-watering/ManualWateringCard.jsx
  WebClient/src/components/quick-controls/QuickControlCard.jsx
  WebClient/src/components/soil-humidity/SoilHumidityAlert.jsx
  WebClient/src/components/soil-humidity/SoilHumidityInput.jsx
  WebClient/src/components/watering-automatic/AutomaticWateringCard.jsx
  WebClient/src/pages/landing-page/LandingPage.jsx
Labels: bug, release

#76 Bugfix/UI and darkmode
  WebClient/index.html
  WebClient/src/App.css
  WebClient/src/components/Dashboard/Widget/WidgetBodyTemplate.jsx
  WebClient/src/components/ThemeProvider.jsx
  WebClient/src/components/activity-history/ActivityHistoryCard.jsx
  WebClient/src/components/air-humidity/AirHumidityLatestCard.jsx
  WebClient/src/components/light/LightDisplayCard.jsx
  WebClient/src/components/manual-watering/ManualWateringCard.jsx
  WebClient/src/components/quick-controls/QuickControlCard.jsx
  WebClient/src/components/soil-humidity/SoilHumidityAlert.jsx
  WebClient/src/components/soil-humidity/SoilHumidityInput.jsx
  WebClient/src/components/soil-humidity/SoilHumidityLatestCard.jsx
  WebClient/src/components/watering-automatic/AutomaticWateringCard.jsx
  WebClient/src/components/watering-prediction/WateringPredictionCard.jsx
Labels: bug, feature

#81 toggle mode
  WebClient/src/App.jsx
  WebClient/src/components/ThemeProvider.jsx
  WebClient/src/components/temperature/TemperatureWidget.jsx
  WebClient/src/components/temperature/TemperatureWidget.test.jsx
  WebClient/src/pages/navbar/Navbar.jsx
Labels: bug
